#version: "3.9"
services:
  nginx:
    depends_on:
      - php
    image: nginx:1.27-alpine
    ports:
      - "8081:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      #- ./www:/usr/share/nginx/html
      - ./www:/var/www/html
  php:
    image: php:8.2-fpm
    container_name: lab2_php
    volumes:
      - ./www:/var/www/html
    expose:
      - "9000"